language: node_js
node_js:
  - "4.2"

before_install: gem install scss-lint

script:
  - npm run lint
  - npm test
  - npm run build

after_success:
  - tar -zcvf build.tar.gz ./build

deploy:
  provider: releases
  file: "build.tar.gz"
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true